name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install prerequisites
      run: sudo apt-get update && sudo apt-get install -y build-essential clang make
    - name: Build project
      run: |
        if ! make build; then
          echo "Build failed"
          exit 1
        fi
    - uses: actions/upload-artifact@v4
      with:
        name: simplemath
        path: simplemath
